# Generated by Django 5.0.2 on 2024-02-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Inhalt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titel',
        ),
    ]
