# Generated by Django 5.0.2 on 2024-02-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='Slug',
        ),
    ]
