# Generated by Django 5.0.2 on 2024-02-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_slug_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Inhalt',
            new_name='inhalt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Titel',
            new_name='titel',
        ),
    ]
