# Generated by Django 5.0.2 on 2024-02-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-Erstellt']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='aktualisiert',
            new_name='Aktualisiert',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='erstellt',
            new_name='Erstellt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='inhalt',
            new_name='Inhalt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titel',
            new_name='Titel',
        ),
    ]
