# Generated by Django 5.0.2 on 2024-02-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
    ]
