# Generated by Django 5.0.2 on 2024-02-27 13:23

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_slug_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Inhalt',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
