# Generated by Django 5.0.2 on 2024-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_post_inhalt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Inhalt',
            field=models.TextField(),
        ),
    ]
